// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: idk.sql

package db

import (
	"context"
)

const getUserById = `-- name: GetUserById :one
SELECT uuid, username, infos, created_at FROM user WHERE uuid = ?
`

func (q *Queries) GetUserById(ctx context.Context, uuid string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserById, uuid)
	var i User
	err := row.Scan(
		&i.Uuid,
		&i.Username,
		&i.Infos,
		&i.CreatedAt,
	)
	return i, err
}
