// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type AithDbManager struct {
	DbVersion int64
}

type Conversation struct {
	ID               int64
	UserID           int64
	ConversationType string
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type Message struct {
	ID             int64
	ConversationID int64
	Role           string
	Content        string
	CreatedAt      time.Time
}

type User struct {
	Uuid      string
	Username  string
	Infos     sql.NullString
	CreatedAt time.Time
}
